// Part04_React/Chap03_Todo/components/TodoForm.js

import React from 'react'

export const TodoForm = () => {

    return (
        <form >
            <div className="input-group">
                <input type="text" className="form-control" />
                <div className="input-group-append">
                    <button type="submit" className="btn btn-primary mr-1">Submit</button>
                </div>
            </div>  
        </form>
    )
    
}

// Part03_Angular/Chap03_Todo/components/TodoForm.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'todoForm',
    template: `
        <form [formGroup]="todoForm">
            <div class="input-group">
                <input type="text" class="form-control"/>
                <div class="input-group-append">
                    <button type="submit" class="btn btn-primary mr-1">Submit</button>
                </div>
            </div>
        </form>
  `,
    styles: [``]
})
export class TodoFormComponent {

}
